PaloAltoNetworks/pan-os-codegen

- assets/pango/logging.go
Terraform provider build for goos `freebsd` goarch `arm`fails when untyped int constant 4294967296 is in use
```
⨯ release failed after 12s                 error=failed to build for freebsd_arm_6: exit status 1: # github.com/PaloAltoNetworks/pango
../pango/logging.go:37:37: cannot use 1 << 32 (untyped int constant 4294967296) as LogCategory value in constant declaration (overflows)
```
https://github.com/PaloAltoNetworks/terraform-provider-panos/actions/runs/10835988398/job/30068711510
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
> chore: fix iota

- pkg/properties/normalized.go
- pkg/schema/object/object.go
- specs/schema/object.schema.json
Add resource-level descriptions for the terraform provider. This is mainly used for documentation.
Closes: #159
> feat: Add resource-level description to specifications

- assets/pango/client.go
- assets/pango/util/pangoclient.go
Retrieving both SystemInfo and Plugins during Initialize() call slows down client setup, which can lead to large slow down for some operations (e.g. terraform provider tests run twice as long due to that).
This commit defers initialization of both to when data is accessed by calling new SystemInfo() and Plugins() methods. The old behavior can still be done when needed by explicitly calling RetrieveSystemInfo() and RetrievePlugins() after a call to Initialize().
> feat: Defer retrieval of system info and plugin data

- assets/pango/client.go
- assets/pango/logging.go
- cmd/codegen/config.yaml
- pkg/translate/terraform_provider/template.go
- pkg/translate/terraform_provider/terraform_provider_file.go
> Feat terraform sdk logging

- specs/schema/spec.schema.json
Add missing `name` property for `codegen_overrides.terraform` in specs schema.
Make valid specs pass schema check.
Run schema check.
- Bug fix (non-breaking change which fixes an issue)
> fix(specs/schema): Add missing name property in terraform overrides

- pkg/properties/normalized.go
- pkg/schema/object/object.go
- pkg/translate/terraform_provider/funcs.go
- specs/schema/object.schema.json
When creating list resources (e.g. panos_addresses, panos_security_policy), PANOS objects are nested within a list/map attribute, but this attribute has no description. This PR allows us to add descriptions to those attributes.
Closes: #144
> feat: Add a list/map description for list resources.

- .github/workflows/pr_ci.yml
- assets/terraform/internal/manager/uuid_test.go
Add execution of tests for both codegen and generated code.
Add support for generating terraform provider.
Additionally - unpin official actions version (pinning is recommended for 3rd party).
Extend code verification with tests and coverage for all supported code.
Locally using act.
- New feature (non-breaking change which adds functionality)
> ci: Add tests execution and TF provider support

- pkg/translate/imports.go
- templates/sdk/service.tmpl
Adding and removing items from the imports location list is currently implemented in a non-atomic way, by first reading a list of items from the server, updating it locally, and sending a new list to the server.
Introduce a (per-resource, per-location) lock to all resources that require modifications of the import list so that those operations are done sequentially.
Closes: #203
> Add imports location lock to serialize non-atomic operations

- assets/terraform/internal/manager/uuid.go
- assets/terraform/test/resource_security_policy_test.go
Rework how entries from the plan are marshaled into MultiConfig updates and ensure that the order is preserved.
Closes: #278
> bug: Make sure that entries created during CreateMany() call are in correct order

- specs/objects/external-dynamic-list.yaml
Most of the initial spec has already been pushed as part of #186 so this only fixes missing enum values.
> feat(specs): Add missing enum values to panos_external_dynamic_list

- assets/terraform/test/resource_ipsec_crypto_profile_test.go
When creating panos_ipsec_crypto_profile resource, one of arguments was not named correctly and the created object was missing data, failing the test.
> fix(tests): Fix panos_ipsec_crypto_profile acceptance tests

- assets/terraform/internal/manager/entry.go
- assets/terraform/internal/manager/entry_test.go
- assets/terraform/test/resource_addresses_test.go
> fix: UpdateMany() logic to properly delete and update resources

- assets/terraform/internal/manager/entry.go
- assets/terraform/internal/manager/uuid.go
- assets/terraform/test/resource_addresses_test.go
- assets/terraform/test/resource_security_policy_test.go
- pkg/translate/terraform_provider/template.go
- pkg/translate/terraform_provider/terraform_provider_file.go
Plural resources (like panos_addresses or panos_security_policy) can have an empty set of entries, and this should be properly handled during updates.
> fix: Properly handle empty plural resources

- specs/objects/profiles/file-blocking.yaml
Add vsys as a valid location, update parameter descriptions.
Bug fix, docs update
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
> fix(specs): Update file blocking security profile

- assets/terraform/examples/resources/panos_security_policy/resource.tf
- assets/terraform/examples/resources/panos_security_policy_rules/resource.tf
- assets/terraform/test/resource_security_policy_test.go
- specs/policies/security-policy-rule.yaml
This was erroneously changed into a simple string attribute
> fix(specs): Make security policy destination zones a list

- assets/terraform/test/resource_dynamic_updates_test.go
It seems it's possible to create panos_dynamic_updates resource referencing a non-existent template, and PAN-OS will happily create a template implicitly. Without dependencies between panos_dynamic_updates and panos_template it's possible that the test will fail because template was already created and we don't allow management of resources that were already present before initial Create().
> fix(tests): Establish terraform dependencies between resources

- specs/objects/profiles/url-filtering.yaml
XML schema provides default values for some variants (mostly strings) and that gets translated into a terraform attribute that always have a value, breaking server-side validation.
> fix(specs): Remove default value from url_filtering_sec_profile variants

- specs/objects/address.yaml
Generate singular `panos_address` resourve variant to better support usecase when address objects are referenced from other resources (e.g. `panos_security_policy`) and list of address objects is modified.
> feat(specs): Generate singular variant for panos_address resource

- pkg/properties/normalized.go
- pkg/translate/terraform_provider/funcs.go
- pkg/translate/terraform_provider/template.go
- specs/policies/security-policy-rule.yaml
For some list attributes, PAN-OS doesn't care about a specific element order, so render those attributes as sets instead in terraform.
> fix: Support rendering of spec lists as unordered sets

- specs/policies/decryption-policy.yaml
- specs/policies/network-address-translation.yaml
Mark uuid attributes in policy resources (i.e. nat policies, decryption policies) as private, removing them from terraform state. This decreases the verbosity of the diff on policy changes.
> feat(specs): Mark policy resource uuid attributes as private

- .github/workflows/pr_ci.yml
- pkg/translate/terraform_provider/terraform_provider_file.go
GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> ci: Pin GitHub Actions

- assets/pango/movement/movement.go
- assets/pango/movement/movement_test.go
- assets/terraform/test/resource_security_policy_rules_test.go
- assets/terraform/test/resource_security_policy_test.go
- pkg/translate/terraform_provider/terraform_provider_file.go
The logic used to generate an expected list of items did not properly handle some cases for a "direct" PositionAfter case, resulting in a crash.
Closes: #447
> fix: Properly initialize an expected order of entries when generating movement actions

- assets/terraform/test/ephemeral_api_key_test.go
- assets/terraform/test/resource_addresses_test.go
- pkg/translate/structs.go
- templates/sdk/config.tmpl
- templates/sdk/entry.tmpl
In some circumstances (non-list parameter with explicit "name" attribute)
it was possible to generate XML struct that cannot be marshaled into an XML
document due to XMLName being different from the name tag in a parent structure.
> fix: Drop XMLName struct field where not needed

- assets/pango/example/main.go
- assets/terraform/test/resource_address_group_test.go
- assets/terraform/test/resource_addresses_test.go
- assets/terraform/test/resource_administrative_tag_test.go
- assets/terraform/test/resource_custom_url_category_test.go
- assets/terraform/test/resource_service_group_test.go
- assets/terraform/test/resource_service_test.go
- pkg/properties/normalized.go
- pkg/translate/structs.go
- pkg/translate/structs_test.go
- pkg/translate/terraform_provider/funcs.go
- pkg/translate/terraform_provider/terraform_provider_file.go
- templates/sdk/location.tmpl
Before, most shared locations were rendered as boolean types. This
however was not always the case, for some shared locations additional
attributes were needed and so those were rendered as objects, possibly
leading to confusion.
Make it so all shared locations are always objects (and structures in Go SDK),
some of which have no attributes/fields.
> feat: Unify location types, making a shared location an (optionally) empty object

- pkg/properties/normalized.go
- pkg/schema/parameter/parameter.go
- pkg/translate/terraform_provider/funcs.go
For future use, some specs will have multiple <choice> XML nodes within a single parent, and those should not all be validated within terraform against each other.
> feat(codegen): Add support for multiple variant groups within single spec

- assets/terraform/internal/provider/errors.go
- assets/terraform/internal/provider/position.go
- assets/terraform/test/resource_security_policy_rules_test.go
- pkg/translate/terraform_provider/device_group_parent_crud.go
- pkg/translate/terraform_provider/funcs.go
- pkg/translate/terraform_provider/template.go
- pkg/translate/terraform_provider/terraform_provider_file.go
By using terraform types for locations and positions we allow use of variables to populate those fields wholesale, and not on by-attribute basis.
This fixes usage of variables to provide location and position in resources.
> fix(terraform): Use terraform types for position and location struct members

- assets/terraform/test/resource_security_policy_rules_test.go
- pkg/translate/terraform_provider/template.go
During ValidateConfig() attributes that are computed from functions and variables are not yet known, and their validation must be skipped.
> fix(terraform): Only validate position when attribute is known

- assets/terraform/test/resource_tunnel_interface_test.go
- pkg/translate/terraform_provider/funcs.go
- specs/network/interface/tunnel.yaml
Add a missing template import location for the tunnel interface, and improve codegen
to set default values for the import attribute within terraform locations.
> fix(specs,codegen): Add template import location for tunnel interfaces

- assets/pango/locking/locking.go
- assets/terraform/test/resource_ethernet_interface_test.go
- pkg/translate/imports.go
- templates/sdk/service.tmpl
Some of the operations done across both Go SDK and terraform provider must be serialized in order to ensure consistent state on the device.
Introduce locking package with `locking.GetMutex(locking.LockCategory, string)` signature that allows us to request locks as needed from both Go SDK (e.g. for importing interfaces into virtual systems) and Terraform (e.g. for importing certificates).
> feat(gosdk): Add global locks manager to serialize some operations

- assets/pango/util/comparison.go
- assets/pango/util/member.go
- pkg/properties/normalized.go
- pkg/translate/imports.go
- pkg/translate/structs.go
- pkg/translate/structs_test.go
Some resources defined in XML schema describe lists of fundamental int64 types. Improve codegen to properly generate structures and marshalling & unmarshalling for int64 lists and add util helpers to convert from Go types to MemberType objects.
> feat(codegen): Add support for int64 member lists

- assets/pango/client.go
- assets/pango/util/pangoclient.go
- pkg/translate/structs.go
ImportFile signature accepted file content as utf-8 string, which would not work properly for
import binary files (like pkcs12 certificate bundles). Change the signature to take []byte array instead.
ExportFile was not setting Content-Type for HTTP request, which would break exporting of files.
> fix(gosdk): change signature of ImportFile to accept content as []byte and set Content-Type during ExportFile

- assets/terraform/internal/manager/config.go
- pkg/translate/terraform_provider/template.go
Config resources can be nested within other resources, and can have xml nodes that
are not part of config structures, and deleting single config object from the server
can remove unrelated configuration.
Instead, fetch existing configuration for the given xpath from the device, and send
back an empty objects, keeping only Misc to make sure anything not managed by this object
is kept as-is.
> fix(terraform): delete config resources by updating them with an empty object

- specs/device/certificate.yaml
Introduce Go SDK object that can be read, listed and deleted as well as
a datasource-only terraform resource for device certificates.
> feat(specs): add spec for read-only device certificates

- assets/terraform/test/ephemeral_vm_auth_key_test.go
- pkg/translate/terraform_provider/template.go
Make sure we pass the expected ProviderData object and not the client to ephemeral resources
> fix(terraform): fix type casting panic within ephemeral resources
